### ISSUE TITLE
Update to HA core 2024.2.0 crashes LG-Horizon and HA

### ISSUE THREAD

**Issue by canedje** [Sholofly/lghorizon#100]
**Describe the bug**
LG-Horizon integration is killing HA (HA will not start up but stops at HACS loading)
I'm running LG-Horizon in Holland with a next mini from Ziggo

**To Reproduce**
After update to HA core running HA as Docker under unraid HA won't start up anymore
Stopping on LG-Horizon integration
Integration will not initialize anymore.
I had to switch off integration to let HA to start again
**Expected behavior**

**Screenshots**
![image](https://github.com/Sholofly/lghorizon/assets/23150947/b4d96a82-6be2-4eaa-95b8-b4dd0322b677)

**Version of the component**
latest version 0.5.8

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by golles** [comment]
Came here to report the same. I tried removing the integration, can't add it anymore.

After update:
```
2024-02-07 21:57:43.230 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:57:46.981 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:57:52.112 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:57:59.042 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:58:10.465 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:58:29.018 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:58:40.431 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-07 21:59:02.949 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 21:59:40.513 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-07 22:00:08.887 ERROR (SyncWorker_10) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
```

Add integration:
```
2024-02-07 22:02:40.467 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ***@***.nl for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 442, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError: Global task timeout
2024-02-07 22:02:40.493 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2024-02-07 22:02:57.848 ERROR (SyncWorker_29) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 22:03:01.597 ERROR (SyncWorker_29) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 22:03:04.771 ERROR (SyncWorker_29) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 22:03:10.742 ERROR (SyncWorker_29) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
2024-02-07 22:03:21.099 ERROR (SyncWorker_29) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
```

**Comment by rzantengmail** [comment]
Same issue here

**Comment by snhnic** [comment]
Same problem

**Comment by Martijn085** [comment]
Same issue here!

**Comment by danema** [comment]
Same here

**Comment by deeg61** [comment]
same problem and even more ad ons are not longer working

**Comment by Jordenjj** [comment]
It's not 2024.2. A restart on 2024.1 broke it too. Something's probably changed in the api call.

**Comment by Dominic-070** [comment]
same here

**Comment by canedje** [comment]
@Jordenjj Then it is a coincidence it happende exactly after an update

**Comment by snhnic** [comment]
I agree with canedje. Hopefully sholofly has time to look into this

**Comment by supergroover** [comment]
Same here. 

#101

**Comment by johnstan** [comment]
Same here

**Comment by Sholofly** [comment]
Hi all, thanks for the feedback. Unfortunately I lack the time to dive into this before at least Saturday.  Good news is that I experience the same on my setup so reproduction won't be an issue. As soon I have something to tell you, I will let you know!

**Comment by johnstan** [comment]
Thanks @Sholofly, very much appreciate all of your work!

**Comment by Mgeeve** [comment]
Same problem.
Unfortunately going back to previous version didn't solve it, can't get it to work anymore

**Comment by JBakers** [comment]
> Hi all, thanks for the feedback. Unfortunately I lack the time to dive into this before at least Saturday.  Good news is that I experience the same on my setup so reproduction won't be an issue. As soon I have something to tell you, I will let you know!

I bet you're occupied celebrating carnaval!

Alaaf! 😉

**Comment by Sholofly** [comment]
No Carnaval but debugging for me ;). It looks like the issue is a PEBCAK one. Used an old URL that stopped working recently. Sorry for the inconvenience all! Update to 0.5.9 and you should be good to go again. Please let me know if you still experience the  mqtt token issue.

**Comment by canedje** [comment]
Yes!!!! Thanks for the afford.
It is working again over here

**Comment by snhnic** [comment]
Looks okay. Thanks

**Comment by StevoNL** [comment]
You hero!

**Comment by johnstan** [comment]
Superstar!

**Comment by Jordenjj** [comment]
Thanks sholo!!

**Comment by Rheugo** [comment]
Great job!! Thanks!

**Comment by golles** [comment]
Thanks Rudolf!
You should consider adding some sort of donation method to your GitHub page. During the blackout period, I realized how much my smart home relies on this integration, so I would be more than happy to buy you a coffee

**Comment by Sholofly** [comment]
Hi @golles, thanks you Sander, happy to help! Actually,  there's a link in the docs (button on the top) for buy me a coffee:https://www.buymeacoffee.com/sholofly
So feel free 😊
