### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by golles** [Sholofly/lghorizon#142]
**Describe the bug**
Just saw your latest release and updated

**To Reproduce**
1. Start HA
2. Integration fails to load

**Expected behavior**

**Screenshots**

**Version of the component**
dev, [9b5a690](https://github.com/Sholofly/lghorizon/commit/9b5a6903d675f71e49571599c20b16e696f400ab)

**Logging**
```
2024-10-26 17:48:27.343 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *** for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 58, in async_setup_entry
    profile_id=entry.data[CONF_PROFILE_ID],
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'profile_id'
```

**Additional context**

**Comment by Sholofly** [comment]
You are quick. I'malready testing a new release ;)

**Comment by golles** [comment]
Deleting the integration and adding it again works fine
