### ISSUE TITLE
Channel 999 not working (NL, Ziggo)

### ISSUE THREAD

**Issue by golles** [Sholofly/lghorizon#15]
**Describe the bug**
Channel 999 (NPO 1 UHD, worldcup) is causing an error.
I've the idea this might be very similar to the issue I had with the previous integration and channel 14 (Ziggo Sport).

**To Reproduce**
1. Go to channel 999 on the mediabox (tv remote)
2. Error in the log

**Expected behavior**
In an ideal world the integration should see this channel, with an image and the current program name.

**Screenshots**

**Version of the component**
Just pulled your `dev` branch

**Logging**
```
2022-11-25 20:14:06.019 ERROR (Thread-106 (_thread_main)) [lghorizon.lghorizon_api] Full message: {'version': '1.4.1', 'type': 'CPE.uiStatus', 'source': '3C36E4-EOSSTB-003926772108', 'messageTimeStamp': 1669403644226, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1669402258378, 'source': {'channelId': 'NL_000207_019518', 'eventId': 'crid:~~2F~~2Fgn.tv~~2F22430094~~2FEP044898230020,imi:ab76b7f1351c75dd815695e983a3a06f48a52c03'}}, 'uiState': {}}}
2022-11-25 20:14:06.021 ERROR (Thread-106 (_thread_main)) [lghorizon.lghorizon_api] ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 269, in _on_mqtt_message\n    self._handle_box_update(deviceId, message)\n', '  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 298, in _handle_box_update\n    channel = self._channels[replayEvent.channelId]\n', "KeyError: 'NL_000207_019518'\n"]
```
Let me know if you need more logs (debug).

**Additional context**

**Comment by Sholofly** [comment]
Hi @golles Thank you for your report. I've updated the component. The issue should be resolved now.

**Comment by golles** [comment]
I can confirm the fix, thanks!
