### ISSUE TITLE
Error setting up entry Virgin Media for lghorizon

### ISSUE THREAD

**Issue by happyhammer7** [Sholofly/lghorizon#36]
I am having issues with this plugin whenever I do a restart/reset of home assistant. Seems to drop connection and won't re-establish. Sometimes, reloading or disabling and enabling the integration will fix the issue but this does not always work. Seems to be an issue with the accessToken - 

Error setting up entry Virgin Media for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 267, in connect
    self._obtain_mqtt_token_gb()
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 256, in _obtain_mqtt_token_gb
    self._session.headers["x-oesp-token"] = self._auth.accessToken
AttributeError: 'LGHorizonAuth' object has no attribute 'accessToken'

**Comment by Sholofly** [comment]
Hi @happyhammer7 Thank you for submitting your issue. Have you enabled debug logging?

**Comment by Sholofly** [comment]
@happyhammer7 How are things going?

**Comment by happyhammer7** [comment]
Hi it seems to be working now. A strange issue but I left it about 48 hours or so and seems to be working again. Wonder if it is an issue from Virgin's side?
