### ISSUE TITLE
doesnt seem to work anymore - handshake error

### ISSUE THREAD

**Issue by steuerzentrale** [Sholofly/lghorizon#37]
**Describe the bug**
The integration doesnt work anymore. A restart of HA nor a restart of the integration helped. I use the integration in Switzerland with UPC.

**Version of the component**
newest version as of January 14 2023

 Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest 

Logger: homeassistant.config_entries
Source: custom_components/lghorizon/__init__.py:50
Integration: LG Horizon (documentation, issues)
First occurred: 20:21:37 (1 occurrences)
Last logged: 20:21:37

Error setting up entry mailgraf@me.com for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 272, in connect
    self._mqttClient.connect()
  File "/usr/local/lib/python3.10/site-packages/lghorizon/models.py", line 319, in connect
    self._mqtt_client.connect(self._brokerUrl, 443)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1080, in reconnect
    sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3713, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3797, in _do_handshake
    raise WebsocketConnectionError("WebSocket handshake error")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error

**Comment by canedje** [comment]
Same over here.
Ziggo holland.
Integration gives an error. After Error I did remove HACS integration and directory. Restart HA
After that: 
Reinstall HACS LG Horizon
Reinstall integration, giving error:
![image](https://user-images.githubusercontent.com/23150947/212493537-82d2a986-21df-4cb2-b525-fbbaa21a22ed.png)

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/lghorizon/__init__.py:50
Integration: LG Horizon (documentation, issues)
First occurred: 20:42:55 (2 occurrences)
Last logged: 20:43:44

Error setting up entry canedje for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 272, in connect
    self._mqttClient.connect()
  File "/usr/local/lib/python3.10/site-packages/lghorizon/models.py", line 319, in connect
    self._mqtt_client.connect(self._brokerUrl, 443)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1080, in reconnect
    sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3713, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3797, in _do_handshake
    raise WebsocketConnectionError("WebSocket handshake error")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error
```

**Comment by Dimitry1977** [comment]
Here in Belgium the same On Telenet.
Telenet Tv app Remote also not working.
So I think it’s not a bug in the app. But with horizon.

**Comment by canedje** [comment]
I just did rollback to version 4.1 and working again,
Only sensor name changed now to media_player.mediabox

**Comment by Recte** [comment]
+1, Ziggo holland

21:35 Confirmed, working again

**Comment by Dimitry1977** [comment]
4.2 working again for me

**Comment by canedje** [comment]
> 

?? oke
will try also.

EDIT: same here working again Only name stays media_payer.mediabox
EDIT2: Apologize I did change the name myzelf in the past. So it is just working fine again

**Comment by steuerzentrale** [comment]
> 

can confirm that, seems to be working. maybe it was an error on the side of the provider?

**Comment by Sholofly** [comment]
Thank you for reporting. I can confirm this was an issue on the liberty global side.
