### ISSUE TITLE
Thread-9 (_thread_main)) [lghorizon.lghorizon_api] Could not handle status message

### ISSUE THREAD

**Issue by JBakers** [Sholofly/lghorizon#45]
Just updated to 

Home Assistant 2023.2.1
Supervisor 2023.01.1
Frontend-versie: 20230202.0 - latest

Checked the logs and see these errors.
I both have a Ziggo Next box and a Next Mini. (Not sure if the Next Mini even applies here)

2023-02-03 20:22:30.319 ERROR (Thread-9 (_thread_main)) [lghorizon.lghorizon_api] Could not handle status message

2023-02-03 20:22:30.328 ERROR (Thread-9 (_thread_main)) [lghorizon.lghorizon_api] Full message: {'version': '1.4.1', 'type': 'CPE.uiStatus', 'source': '3C36E4-EOSSTB-003873640001', 'messageTimeStamp': 1675452149398, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1675446521193, 'source': {'channelId': 'NL_000090_019492', 'eventId': 'crid:~~2F~~2Fgn.tv~~2F8951929~~2FEP028286950071,imi:cc200fd3f3c7982b5c35faf0622ead0f29cc79a8'}}, 'uiState': {}}, 'id': '81dmVeAE'}

2023-02-03 20:32:51.017 ERROR (Thread-9 (_thread_main)) [lghorizon.lghorizon_api] Could not handle status message

2023-02-03 20:32:51.019 ERROR (Thread-9 (_thread_main)) [lghorizon.lghorizon_api] Full message: {'version': '1.4.1', 'type': 'CPE.uiStatus', 'source': '3C36E4-EOSSTB-003873640001', 'messageTimeStamp': 1675452770575, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1675446521193, 'source': {'channelId': 'NL_000088_019251', 'eventId': 'crid:~~2F~~2Fgn.tv~~2F10878060~~2FEP033716750113,imi:609a396a6deb5b5396c7c688982034f461606d16'}}, 'uiState': {}}}

2023-02-03 20:48:40.748 ERROR (SyncWorker_2) [lghorizon.lghorizon_api] Unable to fetch recording capacity...

**Comment by JBakers** [comment]
Now getting this, probably the same:

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py:299
First occurred: 18:48:59 (1 occurrences)
Last logged: 18:48:59

Full message: {'version': '1.4.1', 'type': 'CPE.uiStatus', 'source': 'E0B7B1-APLSTB-300152980904', 'messageTimeStamp': 1676396939482, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1676060500266, 'source': {'channelId': 'NL_000091_019490', 'eventId': 'crid:~~2F~~2Fgn.tv~~2F20867050~~2FEP043092080015,imi:59d622c0b654a908d1ee85ebe9800b3ceec384c6'}}, 'uiState': {}}}

**Comment by Sholofly** [comment]
Hi @JBakers It looks like it isn't able to find the channel information in the API. It usually starts when you are changing to an unknown channel. Can you track if it happens at a specific channel?

**Comment by Sholofly** [comment]
I've updated the component to get more detailed error info. Please update and check the logs for errors once again. It should contain some extra info when it happens again.

**Comment by JBakers** [comment]
These are the errors I'm getting now.
But i haven't even turned the next on.
This is just after the update/reboot.

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.10/site-packages/backoff/_common.py:120
First occurred: 17:13:24 (1 occurrences)
Last logged: 17:13:24

Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://prod.spark.ziggogo.tv/eng/web/vod-service/v2/detailscreen/crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FAZIA0000000000555626?language=nl&profileId=4504e28d-c1cb-4284-810b-f5eaab06f034&cityId=121. Error:403 Client Error: Forbidden for url: https://prod.spark.ziggogo.tv/eng/web/vod-service/v2/detailscreen/crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FAZIA0000000000555626?language=nl&profileId=4504e28d-c1cb-4284-810b-f5eaab06f034&cityId=121)

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py:300
First occurred: 17:13:24 (1 occurrences)
Last logged: 17:13:24

Could not handle status message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 355, in _do_api_call
    api_response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://prod.spark.ziggogo.tv/eng/web/vod-service/v2/detailscreen/crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FAZIA0000000000555626?language=nl&profileId=4504e28d-c1cb-4284-810b-f5eaab06f034&cityId=121

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 298, in _on_mqtt_message
    self._handle_box_update(deviceId, message)
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 343, in _handle_box_update
    raw_vod = self._do_api_call(f"{self._country_settings['api_url']}/eng/web/vod-service/v2/detailscreen/{titleId}?language={self._country_settings['language']}&profileId=4504e28d-c1cb-4284-810b-f5eaab06f034&cityId={self._customer.cityId}")
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 359, in _do_api_call
    raise LGHorizonApiConnectionError(f"Unable to call {url}. Error:{str(httpEx)}")
lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://prod.spark.ziggogo.tv/eng/web/vod-service/v2/detailscreen/crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FAZIA0000000000555626?language=nl&profileId=4504e28d-c1cb-4284-810b-f5eaab06f034&cityId=121. Error:403 Client Error: Forbidden for url: https://prod.spark.ziggogo.tv/eng/web/vod-service/v2/detailscreen/crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FAZIA0000000000555626?language=nl&profileId=4504e28d-c1cb-4284-810b-f5eaab06f034&cityId=121

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py:300
First occurred: 17:18:04 (1 occurrences)
Last logged: 17:18:04

Could not handle status message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 298, in _on_mqtt_message
    self._handle_box_update(deviceId, message)
  File "/usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py", line 342, in _handle_box_update
    titleId = state_source["titleId"]
TypeError: 'NoneType' object is not subscriptable

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py:301
First occurred: 17:13:24 (2 occurrences)
Last logged: 17:18:04

Full message: {'version': '1.3.18', 'type': 'CPE.uiStatus', 'source': 'E0B7B1-APLSTB-300152980904', 'messageTimeStamp': 1678378402409, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'VOD', 'speed': 1, 'lastSpeedChangeTime': 1678361531911, 'source': {'titleId': 'crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FAZIA0000000000555626'}, 'brandingProviderId': 'provider-MOVIESSERIES', 'relativePosition': 569240}, 'uiState': {}}, 'id': '5g6GPvvM'}
Full message: {'version': '1.3.18', 'type': 'CPE.uiStatus', 'source': 'E0B7B1-APLSTB-300152980904', 'messageTimeStamp': 1678378681986, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'VOD', 'speed': 0, 'lastSpeedChangeTime': 1678361531911, 'source': None, 'relativePosition': 0}, 'uiState': {}}}

**Comment by Sholofly** [comment]
Are you sure neither of your boxes is turned on? It gives a status update of a box that has video on demand playing. Are you able to set your logging to debug, to see why that call is triggered?

**Comment by JBakers** [comment]
Set the lghorizon component to debug logging and rebooted and now I get no errors anymore whatsoever.
Removed the debug logging and also no errors till now.
(ik nie weet nie)

Also see a new update 0.5.0, will install that now

**Comment by Sholofly** [comment]
@JBakers I'm closing this for now. If still experiencing this issue, feel free to reopen.
