### ISSUE TITLE
Integration causing Virgin (GB) TV Go logins to fail after a few hours.

### ISSUE THREAD

**Issue by dickthespoon** [Sholofly/lghorizon#47]
**Describe the bug**
TV360 box from Virgin (GB) added as HA entity using this solution, after a couple of hours seems to fail to connect anymore and also blocks login access to Virgin TV Go app for the rest of the family. I have to disable the integration and then wait for a couple of hours then the family can start logging into the app again.

This does not occur with the old Arris DCX960 integration.

**To Reproduce**
Add the Virgin box as described in the instructions, wait  a couple of hours the box becomes unavailable on the HA overview dashboad (just a grey box with no power button), then all family members using the Virgin TV Go app fail to log in with the message login is not possible tray again later.

**Expected behavior**
Usage of the integartion not to fail after a couple of hours and not block access to TV Go

**Version of the component**
All Virgin GB capabable version upto and including 0.4.3

**Logging**
I can't get any logs at the moment as it is extremely disruptive to the family to use the integration. I will enable logging and supply the logs when the family will be out for a period of time that I know will not affect them whilst I do this. Have only just realisised what the common denominator causing the issue that I initially thought was a Virgin one.

**Additional context**
It almost seems as though this integration is causing a spamming of sessions which then causes Virgin to block furher ones when some level is reached.

I am being forced to use the old Arris DCX960 integration at the moment to maintain some sort of continuity.

**Comment by Sholofly** [comment]
Hi @dickthespoon , i am sorry to hear my integration is causing this trouble. At the moment I don't have much time. It can take weeks or even months before I'm able to look at this. As soon I have a new version I will let you know.

**Comment by Sholofly** [comment]
@dickthespoon Have you been able to collect more info about this issue? Since i'm from NL i'm not able to login this system 
 to reproduce it.

**Comment by dickthespoon** [comment]
Hi @Sholofly, still trying to organise a weekend when the family are away and I can reenable with all logging on. I promise I will get them, just family get in the way ;)

**Comment by sichapman** [comment]
I've been having a similar problem where it just stops working; I don't get locked out of the app though, and a simple docker restart to get homeassistant back in action, so it may not be the same thing exactly. Here's the last item in the log before it stops:

(edit: actually I didn't check the app until the next morning so it's entirely possible I did get locked out. I'll try to catch it in the act next time)

```
2023-03-16 00:15:51.996 ERROR (Thread-2 (_thread_main)) [lghorizon.models] Caught exception in on_connect: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)
2023-03-16 00:15:52.003 ERROR (Thread-2 (_thread_main)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/site-packages/lghorizon/models.py", line 314, in _on_mqtt_connect
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/lghorizon/models.py", line 319, in connect
    self._mqtt_client.connect(self._brokerUrl, 443)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)
```

In the days beforehand I also get intermittent Unauthorized errors, these don't cause anything top stop working (at least immediately), but here's one just in case:

```
2023-03-15 00:49:15.069 ERROR (Thread-2 (_thread_main)) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://prod.spark.virginmedia.com/eng/web/linear-service/v2/replayEvent/<SNIP LONG STRING> Error:401 Client Error: Unauthorized for url: https://prod.spark.virginmedia.com/eng/web/linear-service/v2/replayEvent/<SNIP LONG STRING>
2023-03-15 00:49:15.072 ERROR (Thread-2 (_thread_main)) [lghorizon.lghorizon_api] Could not handle status message
2023-03-15 00:49:15.076 ERROR (Thread-2 (_thread_main)) [lghorizon.lghorizon_api] Full message: {'version': '1.3.18', 'type': 'CPE.uiStatus', 'source': 'E0B7B1-APLSTB-300031654704', 'messageTimeStamp': 1678841344223, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1678250342511, 'source': {'channelId': '1599', 'eventId': '<SNIP LONG STRING>', 'trickPlayControl': ['disallowFastForward', 'disallowSkipForward']}}, 'uiState': {}}}
```

**Comment by Sholofly** [comment]
About the last error: Is this still occurring? And is it solved when you restart the integration (reboot HA i.e.)

**Comment by Sholofly** [comment]
@sichapman The first error is about the MQTT connection that's not available. Still happening?

**Comment by sichapman** [comment]
I've been away from my device for a while, but before I left I still noticed the second error (the 401) happening quite often. I don't recall seeing the first one any more.

Restarting homeassistant does seem to clear things up for a while. I never get locked out of the official app either.

**Comment by Sholofly** [comment]
The integration gives up retrying after a while, if the mqtt service is not available. That's by design.
